blueprint:
  name: Leak Detection & Notification
  description: Send a notification when any configured moisture sensor becomes moist
  domain: automation
  input:
    notify_devices:
      name: Mobile devices
      description: "Mobile devices to notify via the companion app."
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true
    notify_services:
      name: Notify services
      description: "Other notification services to use (browsers, cloud, etc.)."
      default: []
      selector:
        entity:
          domain: notify
          multiple: true
    moisture_sensors:
      name: Moisture Sensors
      description: 'Select the moisture sensors to monitor'
      selector:
        entity:
          domain: binary_sensor
          device_class: moisture
          multiple: true

trigger:
  - platform: state
    entity_id: !input moisture_sensors
    to: "on"

variables:
  notify_devices: !input notify_devices
  notify_services: !input notify_services

action:
  - if: "{{ notify_devices | length > 0 }}"
    then:
      - repeat:
          for_each: "{{ notify_devices }}"
          sequence:
            - service: notify.send_message
              target:
                device_id: "{{ repeat.item }}"
              data:
                title: "Leak detected!"
                message: "{{ trigger.to_state.name }} has detected a leak."
  - if: "{{ notify_services | length > 0 }}"
    then:
      - service: notify.send_message
        target:
          entity_id: "{{ notify_services }}"
        data:
          title: "Leak detected!"
          message: "{{ trigger.to_state.name }} has detected a leak."

mode: queued
